// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmZLUuEpblrrFxMcUY5rUbmbKHFbxfNQ',
    appId: '1:804356112154:web:9482c7a13ee1f75bdff6a3',
    messagingSenderId: '804356112154',
    projectId: 'quotes-app-960be',
    authDomain: 'quotes-app-960be.firebaseapp.com',
    storageBucket: 'quotes-app-960be.appspot.com',
    measurementId: 'G-V2WVLNL6PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABerSEMVG95x_UumkZguqmfk0iR1YTa1A',
    appId: '1:804356112154:android:85937d385e36f12ddff6a3',
    messagingSenderId: '804356112154',
    projectId: 'quotes-app-960be',
    storageBucket: 'quotes-app-960be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJR6lg1wqNfXjoVV913MdoqjTI8tuatFc',
    appId: '1:804356112154:ios:524b9e21129839c8dff6a3',
    messagingSenderId: '804356112154',
    projectId: 'quotes-app-960be',
    storageBucket: 'quotes-app-960be.appspot.com',
    iosClientId: '804356112154-8ta35uf8ulfooi09utpfgnut155l7ofo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJR6lg1wqNfXjoVV913MdoqjTI8tuatFc',
    appId: '1:804356112154:ios:01cd749802a2bb2adff6a3',
    messagingSenderId: '804356112154',
    projectId: 'quotes-app-960be',
    storageBucket: 'quotes-app-960be.appspot.com',
    iosClientId: '804356112154-chmbl836v3m8rjici90tiagap9ncmb9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp.RunnerTests',
  );
}
